mytask/mysites/urls.py
from django.conf.urls import url
from mysites import views

urlpatterns = [
    url(r'^$', views.ListMySites.as_view(), name='mysites-list'),
    url(r'^sites/$', views.ListMySites.as_view(), name='mysites-list'),
    url(r'^sites/(?P<pk>\d+)/$', views.MySiteDetail.as_view(), name='site-detail'),
    url(r'^summary/$', views.ListMySitesSum.as_view(), name='mysites-summary sum'),
    url(r'^summary-average/$', views.ListMySitesAvg.as_view(), name='mysites-summary avg'),
]

mytask/project_3megawatt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mysites.urls')),
]

mytask/mysites/models.py
from __future__ import unicode_literals

from django.db import models

class MySite(models.Model):
    '''
    To store all my sites with unique identifier as name
    '''
    name = models.CharField(('Site Name'), unique=True, max_length=20)

    def __unicode__(self):
        return '%s' % (self.name.title())

class MySiteValues(models.Model):
    '''
    Store A values of mysite(any site) 
    '''
    a_value = models.DecimalField(("A value"), max_digits=5, decimal_places=2)
    b_value = models.DecimalField(("B value"), max_digits=5, decimal_places=2)
    mysite = models.ForeignKey(MySite, null=True, blank=True)
    date = models.DateField(("When it is"))

    def __unicode__(self):
        return '%s' % (self.mysite.name)

mytask/mysites/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import Sum, Avg

from collections import OrderedDict

from mysites.models import MySite, MySiteValues

class ListMySites(ListView):
    '''
    List all my sites!
    '''
    model = MySite

class MySiteDetail(DetailView):
    '''
    My Sites Details
    '''
    model = MySite

class ListMySitesSum(ListView):
    '''
    Summary - Sum of A values and sum of B values
    '''
    model = MySite
    template_name = 'mysites/mysite_summary.html' 

    def get_context_data(self, **kwargs):
        context = super(ListMySitesSum, self).get_context_data(**kwargs)

        #Python Programming to find sum of A Values and sum of B values
        sum_dict = OrderedDict()
        site_values = MySiteValues.objects.all().order_by('mysite__id').values('mysite__name', 'a_value', 'b_value')
        for value_dict in site_values:
            if sum_dict.has_key(value_dict['mysite__name']):
                sum_dict[value_dict['mysite__name']]['a_sum'] += value_dict['a_value']
                sum_dict[value_dict['mysite__name']]['b_sum'] += value_dict['b_value']
            else:
                sum_dict[value_dict['mysite__name']] = {'a_sum': value_dict['a_value'], 
                                                           'b_sum': value_dict['b_value']}

        context.update({"sum_dict": sum_dict})
        return context

class ListMySitesAvg(ListView):

    '''
    Summary - Average of A values and sum of B values
    '''

    model = MySite
    template_name = 'mysites/mysite_summary_average.html' 

    def get_context_data(self, **kwargs):
        context = super(ListMySitesAvg, self).get_context_data(**kwargs)

        #Using Raw SQL
        sites = MySiteValues.objects.raw("select ms.*, (select avg(msv.a_value) from mysites_mysitevalues msv where msv.mysite_id = ms.id) avg_a_value, (select avg(msv.b_value) from mysites_mysitevalues msv where msv.mysite_id = ms.id) avg_b_value from mysites_mysite ms") 

        #We can also use Django ORM annotate to find avg
        #sites = MySite.objects.annotate(a_avg=Avg('mysitevalues__a_value'), b_avg=Avg('mysitevalues__b_value')) 
        
        context.update({"sites": sites})
        return context

mytask/mysites/templates/base.html
{% load staticfiles %}
<html>
  <head>

    <title>3MW Application Task</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="/static/bootstrap.css" />

   <style>
       #footer {
        background-color: #222222;
        color: #FFFFFF;
        bottom: 0;
        left: 0;
        margin-bottom: 0;
        position: fixed;
        right: 0;
        text-align: center;
       }
   </style>

  </head>

  <body>
      <nav class="navbar navbar-inverse">
          <div id="navbar" class="navbar-collapse">
            <ul class="nav navbar-nav">
                {% if "sites" in request.path %}
                   <li class="active">
                {% else %}
                  <li>
                {% endif %}
                    <a href="/sites">Sites</a>
                  </li>
                {% if "summary" in request.path %}
                  <li class="active">
                {% else %}
                   <li>
                {% endif %}
                    <a href="/summary">Summary</a>
                   </li>
            </ul>
          </div>
      </nav>

      <div class="container">
          {% block content %}
          {% endblock %}
      </div>

<footer id="footer">
   Posted by: OmPrakash  <br/>Contact information: <a href="mailto:omprakash1989@gmail.com">omprakash1989.com</a>
</footer>
  </body>
</html>

mytask/mysites/templates/mysites/mysite_detail.html
{% extends "base.html" %}

{% block content %}
          <h3>Site Details -{{ object.name }}</h3>
           <table class="table">
            <thead>
              <tr class="info">
                <th>Date</th> <th>A Value</th> <th>B Value</th>
              </tr>
            </thead>
            <tbody>
              {% for mysite_values in object.mysitevalues_set.all %}
                <tr class="active">
                  <td>{{mysite_values.date}}</td>
                  <td>{{mysite_values.a_value}}</td>
                  <td>{{mysite_values.b_value}}</td>
                </tr>
              {% empty %}
                 <li>No site values yet.</li>
              {% endfor %}
            </tbody>
{% endblock %}

mytask/mysites/templates/mysites/mysite_list.html
{% extends "base.html" %}

{% block content %}
          <h3>Sites</h3>
          <ul class="list-group">
            {% for object in object_list %}
               <li class="list-group-item list-group-item-info"><a href="/sites/{{object.id}}/">{{ object.name }}</a></li>
            {% empty %}
               <li>No sites yet.</li>
            {% endfor %}
          </ul>
{% endblock %}

mytask/mysites/templates/mysites/mysite_summary.html
{% extends "base.html" %}

{% block content %}
          <h3>Summary - Sum</h3>
          <a href="/summary/"><button type="button" class="btn btn-primary active">Sum</button></a>
          <a href="/summary-average/"><button type="button" class="btn btn-primary">Average</button></a>
           <br/><br/>
           <table class="table">
            <thead>
              <tr class="info">
                <th>Site</th> <th>A Value</th> <th>B Value</th>
              </tr>
            </thead>
            <tbody>
              {% for site, values in sum_dict.iteritems %}
                <tr class="active">
                  <td>{{site}}</td>
                  <td>{{values.a_sum}}</td>
                  <td>{{values.b_sum}}</td>
                </tr>
              {% empty %}
                 <li>No site values yet.</li>
              {% endfor %}
            </tbody>
{% endblock %}

mytask/mysites/templates/mysites/mysite_summary_average.html
{% extends "base.html" %}

{% block content %}
          <h3>Summary - Average</h3>
          <a href="/summary/"><button type="button" class="btn btn-primary">Sum</button></a>
          <a href="/summary-average/"><button type="button" class="btn btn-primary active">Average</button></a>
          <br/><br/>
           <table class="table">
            <thead>
              <tr class="info">
                <th>Site</th> <th>A Value</th> <th>B Value</th>
              </tr>
            </thead>
            <tbody>
              {% for site in sites %}
                <tr class="active">
                  <td>{{site.name}}</td>
                  <td>{{site.avg_a_value|floatformat:2}}</td>
                  <td>{{site.avg_b_value|floatformat:2}}</td>
                </tr>
              {% empty %}
                 <li>No site values yet.</li>
              {% endfor %}
            </tbody>
{% endblock %}